name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 10
      matrix:
        batch:
          - { suite: "curl",    php: '7.4', package: "php-http/curl-client laminas/laminas-diactoros php-http/message-factory" }
          - { suite: "Socket",  php: '7.4', package: "php-http/socket-client php-http/client-common php-http/message-factory" }
          - { suite: "Guzzle",  php: '7.4', package: "guzzlehttp/guzzle php-http/message-factory" }
          - { suite: "Guzzle",  php: '8.3', package: "guzzlehttp/guzzle php-http/message-factory" }
          - { suite: "Guzzle",  php: '7.4', package: "guzzlehttp/guzzle phpunit/phpunit:^8.5.8 php-http/message-factory" }
          - { suite: "Guzzle",  php: '7.4', package: "guzzlehttp/guzzle phpunit/phpunit:^7.5.20 php-http/message-factory" }
          - { suite: "Buzz",    php: '7.4', package: "kriswallsmith/buzz psr/log php-http/message-factory" }
          - { suite: "Buzz",    php: '8.3', package: "kriswallsmith/buzz psr/log php-http/message-factory" }

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.batch.php }}
          coverage: none
          tools: composer:v2

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download dependencies
        run: |
          composer require ${{ matrix.batch.package }} --no-update
          composer update --prefer-source --no-interaction

      - name: Start test server
        shell: bash
        run: bin/http_test_server > /dev/null 2>&1 &

      - name: Run tests
        run: ./vendor/bin/phpunit --testsuite ${{ matrix.batch.suite }}
